import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import MobileNav from "@/components/ui/mobile-nav";
import { SidebarRight } from "@/components/sidebar-right";
import { ThemeProvider } from "@/components/theme/theme-provider";

export const metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <MobileNav />
            <main className="min-h-screen flex flex-col mx-auto">
              {children}
            </main>
            <SidebarRight />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
